<?php

/*  这个模块主要实现如下功能
 * 1) 默认的首页， 如果是用户为匿名用户访问，则访问到是一般的首页内容，有推荐的小组等 
 * 2） 如果是用户为登录用户，则首页为用户自己的首页，定制推送的内容
*/

/**
 * Implementation of hook_menu().
 */
function frontpage_menu() {
  $items = array();  
   $items['home'] = array(
    'title' => t('Welcome to Home'),
    'page callback' => '_frontpage_home',
    'page arguments' => null,
	'access arguments'=>array('access content'),
    'type' => 'MENU_CALLBACK',
  );
   $items['myhome/%'] = array(
        'title' => 'Home',
    	'title callback' => 'frontpage_page_title',
        'title arguments' => array(1),    
        'page callback' => 'frontpage_myhome',
        'page arguments' => array(1),
        'parent' => '',
        'access arguments' => array('access content'),
   
    );

   
  return $items;
}

function frontpage_page_title($uid){
    $account = user_load($uid);
   return $account->name; 
}

/**
 * Implementation of hook_theme().
 *
 *
 */ 
function frontpage_theme() {
  return array(
   'frontpage_home' => array(
	  'template' => 'frontpage-home',
      'arguments' => array(
            'slider_show'=>null,
            'front_column' => '',
            'front_recent_contents' => '',
  			'front_tag_groups_top' =>'',
  			'front_tag_groups' =>'',
        ),
	),
    
    'frontpage_recommended_groups' => array(
      'arguments' => array(
            'groups'=>null,          		
        ),
	),
    
  );
}


function _frontpage_home () {
    
    $output = '';
    drupal_add_css(drupal_get_path('module','frontpage').'/frontpage.css');
    drupal_set_title('');
    global $user;
    if($user->uid > 0) {    
        $output .= _frontpage_home_heartbeats($user->uid); 
        $output .= _frontpage_home_explore();     
     return $output;
    } else {
        $output = frontpage_featured_groups();
    return $output; 
    }   
}

function frontpage_featured_groups(){
    $output = '';
    $output .='<div class="D_boxhead">';
        $output .='<h3 style="font-size: 1.6em; line-height: 1.2em; color: rgb(51, 51, 51);" class="D_maybeItsTime">';
        $output .='<span>'.t('Do something • Learn something').'</span>';
        $output .='<span>'.t('Share something • Change something').'</span>';
        $output .='</h3>';
    $output .='</div>';
    $output .= '<div class="D_boxsection isNotDivided ">';
        $sql = "select nid from {node} where type='group' and status=1 and promote=1";
        $result = pager_query($sql, 10, 0, "SELECT COUNT(*) FROM {node} WHERE type='group' and status=1 and promote=1");
        while ($entry = db_fetch_object($result)) {
            $node = node_load($entry->nid);
            $output .= _output_group_teaser($node);
        }
    
    $output .= '</div';
    return $output; 
}

/* priviate funciton theme a group teaser 
** @param $node, the group node
**/

function _output_group_teaser($node) {
    $output = '';
    $output .= '<div style="background: url(&quot;http://photos4.meetupstatic.com/photos/event/5/c/5/9/event_40043641.jpeg&quot;) no-repeat scroll center center rgb(102, 102, 102);" class="D_photoGroup">';
    $output .= '<a class="D_photoGroup_link" href="'.$node->path.'">';
    $output .= '<span class="D_photoGroup_bkg"></span>
<span class="D_photoGroup_caption">
<span class="D_photoGroup_caption_body">
<span class="D_photoGroup_name">'. $node->field_site_title[0]['value'].

'</span>
<span class="D_photoGroup_location">
'.$node->field_location[0]['country_name'].' • '.$node->field_location[0]['province_name'].' • '.$node->field_location[0]['lid'].'
</span>

<span class="D_photoGroup_lastMeetup">Latest Meetup: Jul 14, 2011</span>

</span>
</span>
</a>
</div>';
    return $output; 
}

/* priviate function to get an user's personal heartbeat;
**
**
*/
function _frontpage_home_heartbeats($uid){
    $output = '';
    $output .= '<div class="D_box">';
        $output .= '<div class="D_boxbody">';
            $output .= '<div class="D_boxhead">';	
					 $output .= '<h2>'.t('What\'s happening?').'</h2>';
					 $output .= '<ul class="D_actions">';
                     $output .='<li id="D_feedRefreshBtn" class="canDo"><a style="background: url(&quot;http://img1.meetupstatic.com/img/thirdparty/fff/silk/arrow_refresh.png&quot;) no-repeat scroll left top transparent;" class="sprite_action" href="">Refresh</a></li>';
                     $output .= '<li class="canDo">
							<a class="sprite sprite_action page_edit_icon" id="D_unhideBtn" href="javascript:void(0);">Manage feed</a>
						</li>';
                     $output .='<li class="canDo D_splain splainRegistered">
							<a target="_blank" class="sprite_action help_icon sprite splainOver" href="">What\'s this</a>
							
						</li>';
                    $output .= '</ul.';    
            $output .= '</div>';
            
            $output .= '<div class="D_boxsection ">';
            $activity_block = module_invoke('heartbeat','block','view', 'privateheartbeat');  // in the future, this should be replace by other API
            $output .= $activity_block['content'] ;
            $output .= '</div>';
        $output .= '</div>';
    $output .= '</div>';
    return $output; 
}

function _frontpage_home_explore(){

    $output = '';
    $output .= '<div class="D_boxhead">
	
<h2 id="J_yourInterests">发现聚会</h2>

</div>';
    $output .= '<div class="D_boxsection ">	
                    <div class="J_ajaxProgress" id="J_interests">
                        <div class="serendipityLabel">
                        <p>您说您对以下的话题感兴趣，等有人发起类似的话题时候，我们将通过邮件通知您</p>
                        </div>
                    </div>

                </div>            
';
    
    return $output; 

}


/* menu callback
 *
 */
 
 function frontpage_myhome($account) {
    $output = '';
    global $user; 
    drupal_set_title('');
    $output .=  _frontpage_home_heartbeats($user->uid);
    $output .=_frontpage_home_explore();
    
    return $output; 
    
 }



/* hook_menu_alter
* http://drupal.org/node/269913
*/
function frontpage_menu_alter(&$items) {
  /*  global $user; 
    if($user->uid >0) {
        $items['user/%']['title'] = $user->name;
    }
  print_r($items['user/%user/']);*/
}



/* hook_block
 *
 */
 

function frontpage_block($op = 'list', $delta = 0, $edit = array()){
	switch($op){
		case 'list':			
			$blocks[0]['info']=t('Top header left menu');
			$blocks[0]['cache']=BLOCK_NO_CACHE;
            $blocks[1]['info']=t('Top header right menu');
			$blocks[1]['cache']=BLOCK_NO_CACHE;
            $blocks[2]['info']=t('Home Page Welcome block');
			$blocks[2]['cache']=BLOCK_NO_CACHE;
            $blocks[3]['info']=t('Goings-on around your city');
			$blocks[3]['cache']=BLOCK_NO_CACHE;
	
    
			return $blocks;
		case 'view':
			switch($delta){
				case 0:
					$block['subject']=t('Top header left menu');
					$block['content']=frontpage_top_left_menu();
					break;
				case 1:
					$block['subject']=t('Top header right menu');
					$block['content']=frontpage_top_right_menu();
					break;
			    case 2:
					$block['subject']=t('Home Page Welcome block');
					$block['content']=frontpage_home_welcome();
					break;
				case 3:
					$block['subject']=t('Goings-on around your city');
					$block['content']=frontpage_goingon_potomac();
					break;
			}
			return $block;
	}
}

/* block call back 
 * 
 * notice: this part code is dirty, will be refined later.
 */
function frontpage_top_left_menu(){
    $output ='';
    $output .='<div id="C_tabs">

<a href="'.url('og').'">
<span class="C_tabContent">
<span class="C_topBig">
发现
</span>
<span class="C_topSm">
一个聚会
</span>
</span>
</a>


<a href="'.url('group/create').'" class="omnCamp omnic_sn1" id="tabs_start">

<span class="C_startContainer C_tabContent">
<span class="C_topBig">
创建</span>
<span class="C_topSm">
一个小组
</span>
</span>
</a>

<a href="'.url('sponsorships').'" class="omnCamp omnrg_perksheader last" id="tabs_sponsor">
<span class="C_startContainer C_tabContent">
<span class="C_topBig">
赞助</span>
<span class="C_topSm">
小组
</span>
</span>
</a>
</div>';
return $output; 
}

function frontpage_top_right_menu(){
    drupal_add_css(drupal_get_path('module','frontpage').'/frontpage.css');
    $output = '';
    global $user;
    global $base_url;  
    $path = drupal_get_path('module','frontpage');
    $img_path= $base_url.'/'.$path.'/images/house.gif';
    drupal_add_js($path.'/js/frontpage.js'); 
   
    $output .= '<ul id="frontpage-top-right-menu" class="sf-menu">'; 
 //   $output .= '<li class="leaf first">'.l($user->name, 'myhome/'.$user->uid).'</li>';
     if($user->uid) {
        $output .= '<li class="leaf first">'.'<div id="C_welcome"><a class="icon" href="'.url('myhome/'.$user->uid).'"><img alt="Home" class="D_icon" src="'.$img_path.'"></a> <a class="text" href="'.url('myhome/'.$user->uid).'">'.$user->name.'</a></div>'.'</li>';
    }
    $output .= '<li class="whats-new leaf C_userNavItem_less"><a href="">'.t('What\'s New');
    //    $output .= '<span class="unreadCount">1</span>';
    $output .= '</a></li>';
    $output .= '<li class="leaf C_userNavItem_less">'.l(t('Help'),'').'</li>';
   
   if($user->uid) {
    $output .= '<li class="leaf hasDropDown"><a href="'.url('user/'.$user->uid.'/mygroups').'">'.t('My Groups').'</a>';    
        $output .= '<ul style="z-index: 5001;  " class="myGroupsSection">';
            $output .= '<li><a class="C_groupsMenuItem" href="">Beijing Soccer Lovers</a></li>';
            $output .= '<li><a class="C_groupsMenuItem" href="">teemeet</a></li>';
        $output .= '</ul>';        
    $output .= '</li>';
    }
    if($user->uid) {
    $output .= '<li class="leaf ">'.l(t('Account'),'').'</li>';
    $output .= '<li class="leaf last">'.l(t('Log out'),'logout').'</li>';
    } else {
    $output .= '<li class="leaf ">'.l(t('Log in'),'user/login').'</li>';
    $output .= '<li class="leaf ">'.l(t('Sign up'),'user/register').'</li>';
    }
    $output .= '</ul>';
  
    
    return $output; 
}

function frontpage_home_welcome(){
 drupal_add_css(drupal_get_path('module','frontpage').'/frontpage.css');
    $output = '';
    global $user;
    $has_group = false; 
    foreach ($user->og_groups as $key => $val) {
          $links[$key] = l($val['title'], "node/$key") . theme('og_format_subscriber_status', $val);
           $has_group = true;
    }
    $my_groups = theme('item_list', $links);

    $output .='<div class="D_boxbody">
            <div class="D_boxhead">	
            <h1>'.t('欢迎回来,').$user->name. '</h1>';
    $group_output =  $has_group ? $my_groups :  '<strong>您还没有加入任何小组!</strong><br>我们下面准备了一些信息，以方便您找到感兴趣的小组.';      
    $output .= '<div style="margin-top: 1em;" class="storytime">'. $group_output;
$output .= '</div></div></div>';

 return $output; 
}

function frontpage_goingon_potomac(){
    $output = '';
    $output .= '<h3>There are <span class="pop">801</span> Meetups happening near Potomac this week, including:</h3>';
    return $output;
}