<?php
// $Id: devel.module,v 1.258.2.77 2010/08/13 16:46:59 weitzman Exp $
/*group_extensions_menu()
{
    
}*/
define('NODE_TYPE', 'group'); //节点类型

/*function group_extensions_form_alter(&$form, $form_state, $form_id)
{
    if($_GET['q'] == 'node/add/group') print_r($form_id);
}*/
//_form_group_node
function group_extensions_perm()
{
    return array('create group');
}

function group_extensions_menu()
{
    $items['group/create'] = array
    (
        'title' => 'Start a new group!',
        'description' => 'Create a group',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('group_create'),
        'access callback' => 'user_is_logged_in',
        'file' => 'group_form.inc',
    );
    
    $items['group/%/comments'] = array(
    	'title' => t('All Group Reviews'),
        'page callback' => 'group_extensions_comments_list',
        'page arguments' => array(1),                
        'access callback' =>true,
        'type' => MENU_CALLBACK, 
        'file' => 'group.comment.inc',
    );
    $items['groupextension/ajax/postcomment']=array(
		'title'=>t('Post Comment'),
		'page callback'=>'group_extensions_ajax_postcomment',
		'page arguments'=>null,
		'access callback'=>TRUE,
        'type' => MENU_CALLBACK,
        'file' => 'group.comment.inc',
	);
    
    $items['groupextension/allmembers/%']=array(
		'title'=>t('All Members'),
		'page callback'=>'group_extensions_all_group_members',
		'page arguments'=>array(2),
		'access callback'=>TRUE,
        'type' => MENU_LOCAL_TASK,     
        'file' => 'group_extension.members.inc',
	);
    $items['groupextension/allmembers/%/all']=array(
        'title'=>t('All Members'),		
        'type' => MENU_DEFAULT_LOCAL_TASK,   
        'file' => 'group_extension.members.inc',
	);
     $items['groupextension/allmembers/%/leadship']=array(
        'title'=>t('The Leadship Team'),		 
        'page callback'=>'group_extensions_all_leadship_members',
		'page arguments'=>array(2),
		'access callback'=>TRUE,
        'type' => MENU_LOCAL_TASK,
        'file' => 'group_extension.members.inc',
	);    
    
    return $items;    
}


/**
 * Implementation of hook_theme().
 *
 *
 */
function group_extensions_theme() {
  return array(
   'group_extensions_member' => array(	 // theme one member
      'arguments' => array(
            'member'=>null, 
            
        ),
	),
        
  );
}


/*function group_extensions_form_alter(&$form, $form_state, $form_id)
{ 
    if($form_id != FORMID) return;
} */

function group_extensions_nodeapi(&$node, $op, $teaser, $page) 
{
    if($node->type == NODE_TYPE and $node->status != 0 and $op == 'view') 
    {
        $node_timeStamp = dateToStamp($node->field_date_valuable[0][value]);
        if(time() > $node_timeStamp)
        {
            $node->status = 0;
            node_save($node);
        }
    }    
    
    switch ($op) {
    case 'load':    
        if($node->type == NODE_TYPE ) {
             list($txt, $subscription) = og_subscriber_count_link($node);
            $node->og_member_count = (int)$txt;
        }
        
        
    break;
      
    }
    
}

/**
 * dateToStamp()
 * 输入形如 yyyy-mm-dd 的日期返回日期时间戳
 * @param string $date
 * @return void
 */
function dateToStamp($date = '0000-00-00 ignore')
{
    $day = (int)substr($date, 8, 2);
    $month = (int)substr($date, 5, 2);
    $year = (int)substr($date, 0, 4);
    return mktime(0, 0, 0, $month, $day, $year);
}



/* Get all one user's comment for a group node
 * @param $gid, group node nid
 * @param $uid, the user uid
 * return, if there is a value, return , otherwise, 0
 */
function group_extensions_get_my_group_review($gid, $uid){
	$output = '';
        
		// Pre-process variables.
		$nid = $gid;
	
		$query = 'SELECT c.cid as cid, c.pid, c.nid, c.subject, c.comment, c.format, c.timestamp, c.name, c.mail, c.homepage, u.uid, u.name AS registered_name, u.signature, u.signature_format, u.picture, u.data, c.thread, c.status FROM {comments} c INNER JOIN {users} u ON c.uid = u.uid WHERE c.nid = %d and c.uid=%d';
        
		// Start a form, for use with comment control.
		$result = db_query($query,$gid, $uid);

		$num_rows = FALSE;
		
		global $base_path;
		$a= null; 
		while ($comment = db_fetch_object($result)) {
			$num_rows = TRUE;
            $a = $comment; 
		}

		if($num_rows) {           
			return $a; 
		} else {   
			return FALSE;
		}	
}
