<?php
// $Id: devel.module,v 1.258.2.77 2010/08/13 16:46:59 weitzman Exp $
/*group_extensions_menu()
{
    
}*/
define('NODE_TYPE', 'group'); //节点类型

/*function group_extensions_form_alter(&$form, $form_state, $form_id)
{
    if($_GET['q'] == 'node/add/group') print_r($form_id);
}*/
//_form_group_node
function group_extensions_perm()
{
    return array('create group');
}

function group_extensions_menu()
{
    $items['group/create'] = array
    (
        'title' => 'Start a new group!',
        'description' => 'Create a group',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('group_create'),
        'access callback' => 'user_is_logged_in',
        'file' => 'group_form.inc',
    );
    
    $items['group/%/comments'] = array(
    	'title' => t('All Group Reviews'),
        'page callback' => 'group_extensions_comments_list',
        'page arguments' => array(1),                
        'access callback' =>true,
        'type' => MENU_CALLBACK, 
        'file' => 'group.comment.inc',
    );
    $items['groupextension/ajax/postcomment']=array(
		'title'=>t('Post Comment'),
		'page callback'=>'group_extensions_ajax_postcomment',
		'page arguments'=>null,
		'access callback'=>TRUE,
        'type' => MENU_CALLBACK,
        'file' => 'group.comment.inc',
	);
    
    
   
   
    
    return $items;    
}

/*function group_extensions_form_alter(&$form, $form_state, $form_id)
{ 
    if($form_id != FORMID) return;
} */

function group_extensions_nodeapi(&$node, $op, $teaser, $page) 
{
    if($node->type == NODE_TYPE and $node->status != 0 and $op == 'view') 
    {
        $node_timeStamp = dateToStamp($node->field_date_valuable[0][value]);
        if(time() > $node_timeStamp)
        {
            $node->status = 0;
            node_save($node);
        }
    }    
    //if($op == 'insert'){ print_r($node);die;}
}

/**
 * dateToStamp()
 * 输入形如 yyyy-mm-dd 的日期返回日期时间戳
 * @param string $date
 * @return void
 */
function dateToStamp($date = '0000-00-00 ignore')
{
    $day = (int)substr($date, 8, 2);
    $month = (int)substr($date, 5, 2);
    $year = (int)substr($date, 0, 4);
    return mktime(0, 0, 0, $month, $day, $year);
}