<div class="D_box" id="events-list-module">
  <h1 id="welcome-message" class=""> 欢迎标题，设置位置未知 </h1>
  <a href="http://www.meetup.com/SacSwim/suggestion/" id="lma-suggest" class="ghsprite plus_bk for-non-member showJoin J_signupLink J_onClick">加入并开展一个Meetup</a>
  <div id="lma" class="closed">
    <ul class="resetList clearfix" id="events-nav">
      <li class=" selected"><a href="http://www.meetup.com/SacSwim/" id="upcomingTab" class="page-meetups" data-pageto="0" data-op="" data-append="false">Upcoming <span class="tabcount">12</span></a></li>
      <li class=""><a href="http://www.meetup.com/SacSwim/events/past/" id="pastTab" class="page-meetups" data-pageto="0" data-op="past" data-append="false">Past</a></li>
      <li class=""><a href="http://www.meetup.com/SacSwim/events/calendar/" class="page-meetups" data-op="calendar" data-pageto="0" data-append="false">Calendar</a></li>
    </ul>
  </div>
  
  <ul id="ajax-container" class="resetList event-list clearfix">
    <li class="line event-item   hide-tools isFeatured" itemscope="" itemtype="http://data-vocabulary.org/Event"> <span itemprop="eventType" style="display:none;">Meetup</span>
      <div class="featured-callout">
        <div class="featured-callout-wrap">
          <div class="featured-text"> Featured Meetup </div>
          <div class="featured-pointer top"></div>
          <div class="featured-pointer bottom"></div>
        </div>
        <div class="featured-ribbon"></div>
      </div>
      <div class="event-title"> <a href="http://www.meetup.com/SacSwim/events/27200051/" itemprop="url" class="omnCamp omnrv_rv13"><span itemprop="summary">Another Lake Tahoe Training Swim!</span></a> </div>
      <div class="event-meta">
        <ul class="resetList">
          <li class="dateTime">
            <time itemprop="startDate" datetime="2011-08-07T07:00:00-07:00"> <span class="date">Sun Aug 07</span><br>
              <span class="time">7:00 AM</span> </time>
          </li>
          <li class="rsvp-callout-outer"> <a href="http://www.meetup.com/SacSwim/events/27200051/" class="rsvp-callout-rsvp omnCamp omnrv_rv13"> <span class="rsvp-callout-arrow">→</span> RSVP </a> </li>
          <li class="rsvpCount event-count rsvp-meta-subtle-link attending-count"> <a href="http://www.meetup.com/SacSwim/events/27200051/" class="no-underline-link omnCamp omnrv_rv13"> <em>8</em> attending </a> </li>
          <li class="last event-count rsvp-meta-subtle-link"> <a href="http://www.meetup.com/SacSwim/events/27200051/" class="no-underline-link omnCamp omnrv_rv13"> <em>9</em> comments </a> </li>
        </ul>
      </div>
      <div class="event-content"> <span itemprop="location">
        <dl class="event-where">
          <dt class="event-venuename"> <a href="http://www.meetup.com/SacSwim/events/27200051/" class="no-color omnCamp omnrv_rv13">Fleet Feet Sports</a> </dt>
          <dd> 1850 Douglas Blvd # 418, Roseville, CA
            (<a href="http://maps.google.com/maps?q=1850+Douglas+Blvd+%23+418%2C+Roseville%2C+CA" target="_blank">map</a>) </dd>
        </dl>
        </span>
        <ul class="resetList event-rsvpPhotos ">
          <li><a href="http://www.meetup.com/SacSwim/members/11107221/" class="thumb30" title="helen"> <img alt="helen" data-src="http://photos3.meetupstatic.com/photos/member/b/e/0/7/thumb_12348647.jpeg" src="http://photos3.meetupstatic.com/photos/member/b/e/0/7/thumb_12348647.jpeg" style="display: inline; "> </a></li>
          <li><a href="http://www.meetup.com/SacSwim/members/14426205/" class="thumb30" title="Bruce Carso"> <img alt="Bruce Carso" data-src="http://photos3.meetupstatic.com/photos/member/4/7/b/6/thumb_12498358.jpeg" src="http://photos3.meetupstatic.com/photos/member/4/7/b/6/thumb_12498358.jpeg" style="display: inline; "> </a></li>
          <li><a href="http://www.meetup.com/SacSwim/members/10146567/" class="thumb30" title="Myron"> <img alt="Myron" data-src="http://photos2.meetupstatic.com/photos/member/9/f/d/6/thumb_10660918.jpeg" src="http://photos2.meetupstatic.com/photos/member/9/f/d/6/thumb_10660918.jpeg" style="display: inline; "> </a></li>
          <li><a href="http://www.meetup.com/SacSwim/members/13244138/" class="thumb30" title="Shawn C Turner"> <img alt="Shawn C Turner" data-src="http://photos1.meetupstatic.com/photos/member/4/0/1/a/thumb_11116410.jpeg" src="http://photos1.meetupstatic.com/photos/member/4/0/1/a/thumb_11116410.jpeg" style="display: inline; "> </a></li>
          <li><a href="http://www.meetup.com/SacSwim/members/12134294/" class="thumb30" title="Tom"> <img alt="Tom" data-src="http://photos2.meetupstatic.com/photos/member/5/c/6/3/thumb_9743651.jpeg" src="http://photos2.meetupstatic.com/photos/member/5/c/6/3/thumb_9743651.jpeg" style="display: inline; "> </a></li>
          <li><a href="http://www.meetup.com/SacSwim/members/21916261/" class="thumb30" title="Jason Matsushino"> <img src="http://img2.meetupstatic.com/8719071596039115400/img/noPhoto_35.png" data-src="http://img2.meetupstatic.com/8719071596039115400/img/noPhoto_35.png" alt="Jason Matsushino" style="display: inline; "> </a></li>
          <li class="no-member"></li>
          <li class="no-member"></li>
          <li class="no-member"></li>
          <li class="no-member"></li>
          <li class="no-member"></li>
        </ul>
        <div class="event-desc" itemprop="description"> since our swim at Lake Tahoe was SO great, we are going again!  come join us!  water is fabulous and just gorgeous!  
          we'll meet in the morning in the parking lot by Fleet Feet in Roseville (not too far off Highway 80).  Then,  we will carpool/caravan up there. 
          so, whether you're interested in doing a training swim up there, just want to... <a href="http://www.meetup.com/SacSwim/events/27200051/" style="text-transform:uppercase;font-size:9px" class="omnCamp omnrv_rv13">Learn more</a> </div>
        <p class="event-hosts secondaryInfo">Hosted by: <a href="http://www.meetup.com/SacSwim/members/11107221/">helen</a> (Co-Organizer) </p>
        <ul class="resetList event-comments">
          <li class="feed-item-small clearfix" id="comment_30614521_event"> <a href="http://www.meetup.com/SacSwim/members/14426205/" class="thumb30" title="Bruce Carso"><img alt="Bruce Carso" src="http://photos3.meetupstatic.com/photos/member/4/7/b/6/thumb_12498358.jpeg"></a>
            <div class="feed-item-content-small"> <a href="http://www.meetup.com/SacSwim/members/14426205/" class="comment-commenter" title="Bruce Carso">Bruce Carso:</a>
              <p>I am driving up from Placerville tomorrow. I would love to meetup with someone outside the park to share parking cost. Myron if you have that much room I would be happy to join you and share parking cost. Also they park fills up so it will allow another family into the Park. Meet at  Rayley's off of Incline Village Blvd??</p>
              <div class="feed-item-actions D_empty D_less"> Posted 9 hours ago </div>
            </div>
          </li>
          <li class="feed-item-small clearfix last" id="comment_30633291_event"> <a href="http://www.meetup.com/SacSwim/members/21916261/" class="thumb30" title="Jason Matsushino"><img alt="Jason Matsushino" src="http://img1.meetupstatic.com/665964083627134082/img/noPhoto_50.png"></a>
            <div class="feed-item-content-small"> <a href="http://www.meetup.com/SacSwim/members/21916261/" class="comment-commenter" title="Jason Matsushino">Jason Matsushino:</a>
              <p>Coming from Donner, will meet you guys there at 9:30.</p>
              <div class="feed-item-actions D_empty D_less"> Posted 6 hours ago </div>
            </div>
          </li>
        </ul>
      </div>
    </li>
    <li class="event-list-more" id="centerColMeetupListRearguard"> <a href="http://www.meetup.com/SacSwim/?page=1" class="page-meetups D_roundedButton caps" data-pageto="1" data-op="" data-append="true" data-displayold="0">More Meetups <span class="feed-pager-link"></span></a> </li>
  </ul>
</div>

<div id="recentMeetups" class="D_box">
  <h2>Recent Meetups</h2>
  <ul class="resetList event-list clearfix">
    <li class="past line event-item ">
      <p class="event-attended">12 hours ago, 3 swimmers attended </p>
      <a href="http://www.meetup.com/SacSwim/events/23780881/" class="event-title">Annual Donner Lake Open Water Swim -  2.7 Miles</a>
      <ul class="resetList event-rsvpPhotos ">
        <li><a href="http://www.meetup.com/SacSwim/members/11084458/" class="thumb30" title="Patricia Sepulvado"> <img alt="Patricia Sepulvado" data-src="http://photos4.meetupstatic.com/photos/member/8/4/thumb_8460132.jpeg" src="http://photos4.meetupstatic.com/photos/member/8/4/thumb_8460132.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/20356511/" class="thumb30" title="Kathy"> <img alt="Kathy" data-src="http://photos2.meetupstatic.com/photos/member/5/6/9/b/thumb_18862171.jpeg" src="http://photos2.meetupstatic.com/photos/member/5/6/9/b/thumb_18862171.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/13244138/" class="thumb30" title="Shawn C Turner"> <img alt="Shawn C Turner" data-src="http://photos1.meetupstatic.com/photos/member/4/0/1/a/thumb_11116410.jpeg" src="http://photos1.meetupstatic.com/photos/member/4/0/1/a/thumb_11116410.jpeg" style="display: inline; "> </a></li>
      </ul>
      <div class="event-desc"> 30th Annual Donner Lake Open Water Swim
        2.7 MILES SATURDAY, AUGUST 7, 2010 8:30 AM
        Water temp. : 65-68&amp;deg; Truckee, CA. Altitude: 5933 ft. <a href="http://.." target="_blank">http://.....</a>. <a href="http://www.meetup.com/SacSwim/events/23780881/" style="text-transform:uppercase;font-size:9px">Learn more</a> </div>
    </li>
    <li class="past line event-item last">
      <p class="event-attended">Thursday at 6:00 PM, 25 swimmers attended </p>
      <a href="http://www.meetup.com/SacSwim/events/22126171/" class="event-title">Folsom Lake Open Water SWIM AND BBQ!!!</a>
      <ul class="resetList event-rsvpPhotos ">
        <li><a href="http://www.meetup.com/SacSwim/members/10970177/" class="thumb30" title="Bill Roehr"> <img src="http://img2.meetupstatic.com/8719071596039115400/img/noPhoto_35.png" data-src="http://img2.meetupstatic.com/8719071596039115400/img/noPhoto_35.png" alt="Bill Roehr" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/21916261/" class="thumb30" title="Jason Matsushino"> <img src="http://img2.meetupstatic.com/8719071596039115400/img/noPhoto_35.png" data-src="http://img2.meetupstatic.com/8719071596039115400/img/noPhoto_35.png" alt="Jason Matsushino" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/10629083/" class="thumb30" title="Paulo Medina"> <img alt="Paulo Medina" data-src="http://photos2.meetupstatic.com/photos/member/c/9/8/0/thumb_9651584.jpeg" src="http://photos2.meetupstatic.com/photos/member/c/9/8/0/thumb_9651584.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/9447412/" class="thumb30" title="Sean"> <img alt="Sean" data-src="http://photos2.meetupstatic.com/photos/member/2/6/5/1/thumb_6489809.jpeg" src="http://photos2.meetupstatic.com/photos/member/2/6/5/1/thumb_6489809.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/11577708/" class="thumb30" title="Mike White"> <img alt="Mike White" data-src="http://photos3.meetupstatic.com/photos/member/6/c/e/8/thumb_9987880.jpeg" src="http://photos3.meetupstatic.com/photos/member/6/c/e/8/thumb_9987880.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/11898674/" class="thumb30" title="Elijah Li"> <img alt="Elijah Li" data-src="http://photos4.meetupstatic.com/photos/member/5/0/9/8/thumb_9440632.jpeg" src="http://photos4.meetupstatic.com/photos/member/5/0/9/8/thumb_9440632.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/14426205/" class="thumb30" title="Bruce Carso"> <img alt="Bruce Carso" data-src="http://photos3.meetupstatic.com/photos/member/4/7/b/6/thumb_12498358.jpeg" src="http://photos3.meetupstatic.com/photos/member/4/7/b/6/thumb_12498358.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/9166538/" class="thumb30" title="Lora PITTMAN"> <img alt="Lora PITTMAN" data-src="http://photos2.meetupstatic.com/photos/member/1/c/b/8/thumb_10207352.jpeg" src="http://photos2.meetupstatic.com/photos/member/1/c/b/8/thumb_10207352.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/12134294/" class="thumb30" title="Tom"> <img alt="Tom" data-src="http://photos2.meetupstatic.com/photos/member/5/c/6/3/thumb_9743651.jpeg" src="http://photos2.meetupstatic.com/photos/member/5/c/6/3/thumb_9743651.jpeg" style="display: inline; "> </a></li>
        <li><a href="http://www.meetup.com/SacSwim/members/11107221/" class="thumb30" title="helen"> <img alt="helen" data-src="http://photos3.meetupstatic.com/photos/member/b/e/0/7/thumb_12348647.jpeg" src="http://photos3.meetupstatic.com/photos/member/b/e/0/7/thumb_12348647.jpeg" style="display: inline; "> </a></li>
      </ul>
      <p class="event-rating"> They
        
        rated it <img class="D_icon" src="http://img2.meetupstatic.com/03784007994490629714917/img/star_500.png" alt="5.00" title="1 rating for an average of 5.00 out of 5"> <span class="displaynone rating"><span class="average">5.00</span><span class="count">1</span></span> <span class="D_ratingsText D_empty" title="1 rating for an average of 5.00 out of 5"> (1 ratings) </span> and
        
        
        uploaded <a href="http://www.meetup.com/SacSwim/photos/2709911/">3 photos</a> </p>
      <div class="event-desc"> BBQ after this swim, first thursday of each month !! Fun swim
        and fun foods ! This will be a good swim for those getting ready
        for triathlons and Open Water Swims, also... <a href="http://www.meetup.com/SacSwim/events/22126171/" style="text-transform:uppercase;font-size:9px">Learn more</a> </div>
    </li>
  </ul>
  <a href="http://www.meetup.com/SacSwim/events/past/?page=0" style="text-transform:uppercase;" id="seePastMeetups" class="page-meetups D_roundedButton" data-pageto="0" data-op="past" data-displayold="0">See all past Meetups</a>
</div>