<?php

include_once('teemeet_heartbeat.features.inc');

/**
 * Implementation of hook_heartbeat_register_access_types().
 */
function teemeet_heartbeat_heartbeat_register_access_types() {
  return array(
    // Site activity stream is kind of a copy of HeartbeatPublic.
    // It is only to show you how it's done.
    0 => array(
      'name' => 'Site user activity',
      'class' => 'SiteUserActivity',
      'path' => 'site_user_activity.inc',
      'module' => 'teemeet_heartbeat',
      'access' => TRUE
    ),
  );
}
